name: dartpy
description: A library for using dart with python via python's C API
version: 0.0.3
homepage: http://github.com/TimWhiting/dartpy

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.8.3
  ffi: ^2.1.0
  freezed_annotation: ^2.4.1
  args: ^2.4.2

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.6
  ffigen: ^9.0.1
  freezed: ^2.4.2
  build_runner: ^2.4.6

