name: dartpy
description: A library for using dart with python via python's C API
version: 0.0.5
homepage: http://github.com/TimWhiting/dartpy

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.9.0
  ffi: ^2.1.2
  freezed_annotation: ^2.4.1
  args: ^2.5.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.25.7
  ffigen: ^12.0.0
  freezed: ^2.5.3
  build_runner: ^2.4.11

